### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by ShivamKR12** [mandaw2014/mandaw_openworld#3]
PS C:\Users\Shivam\Desktop\voxel 3d\mandaw_openworld-master> & C:/Users/Shivam/AppData/Local/Programs/Python/Python312/python.exe "c:/Users/Shivam/Desktop/voxel 3d/mandaw_openworld-master/main.py"
package_folder: C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina
asset_folder: c:\Users\Shivam\Desktop\voxel 3d\mandaw_openworld-master
screen resolution: (1366, 768)
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "c:\Users\Shivam\Desktop\voxel 3d\mandaw_openworld-master\main.py", line 20, in <module>
    map = Map()
          ^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\mandaw_openworld-master\map.py", line 8, in __init__
    self.terrain = Entity(model = Terrain("heightmap", skip = 8), texture = "colour", scale = 2000, scale_y = 1000, collider = "mesh", tag = "terrain")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Shivam\Desktop\voxel 3d\mandaw_openworld-master\terrain.py", line 24, in __init__
    img = img.resize([self.width, self.depth], Image.ANTIALIAS)
                                               ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by ShivamKR12** [comment]
@mandaw2014
